#!/bin/bash

xhost + 127.0.0.1

docker run --rm -it -e DISPLAY=host.docker.internal:0 -e "JTAG_SERVER=$JTAG_SERVER" -e "JTAG_PASSWD=$JTAG_PASSWD" -v $(pwd):/build chriz2600/quartus-lite:latest /usr/local/bin/quartus_wrapper "$@"
