#!/bin/bash

# Xquartz stuff
xquartz_if_not_running() {
    v_nolisten_tcp=$(defaults read org.macosforge.xquartz.X11 nolisten_tcp)
    v_xquartz_app=$(defaults read org.macosforge.xquartz.X11 app_to_run)

    if [ $v_nolisten_tcp == "1" ]; then
    defaults write org.macosforge.xquartz.X11 nolisten_tcp 0
    fi

    if [ $v_xquartz_app != "/usr/bin/true" ]; then
    defaults write org.macosforge.xquartz.X11 app_to_run /usr/bin/true
    fi

    netstat -an | grep 6000 &> /dev/null || open -a XQuartz
    while ! netstat -an \| grep 6000 &> /dev/null; do
    sleep 2
    done
    export DISPLAY=:0
}

xquartz_if_not_running

xhost + 127.0.0.1

docker run --rm -it -e DISPLAY=host.docker.internal:0 -e "JTAG_SERVER=$JTAG_SERVER" -e "JTAG_PASSWD=$JTAG_PASSWD" -v $(pwd):/build chriz2600/quartus-lite:latest /usr/local/bin/quartus_wrapper "$@"
